# Generated by Django 4.1.5 on 2023-08-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_name_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='author_lower',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kz', 'Қазақ әдебиеті'), ('world', 'Әлем әдебиеті'), ('children', 'Балалар әдебиеті')], max_length=50),
        ),
    ]
