# Generated by Django 4.1.5 on 2023-08-29 03:08

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('books', 'BOOKS'), ('languages', 'LANGUAGES'), ('certificate', 'CERTIFICATE')], max_length=50)),
                ('fullname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=project.utils.datetime_now, editable=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('request_text', models.TextField()),
            ],
        ),
    ]
