# Generated by Django 4.1.5 on 2023-08-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_request_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('books', 'Кітаптар'), ('languages', 'Тіл курстары'), ('certificates', 'Сертификаттар')], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
