# Generated by Django 4.1.5 on 2023-08-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_category_alter_request_request_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
