# Generated by Django 4.1.5 on 2023-08-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=500)),
                ('link', models.CharField(default='', max_length=500)),
                ('type', models.CharField(choices=[('phone_number', 'Номер телефона'), ('whatsapp', 'Whatsapp'), ('email', 'Эл. почта'), ('instagram', 'Instagram'), ('footer', 'Footer')], max_length=100, unique=True)),
            ],
        ),
    ]
